### ISSUE TITLE
Include you .hex file for Bootmapper Client

### ISSUE THREAD

**Issue by Gareth-Rouse** [peverett/YMDK75_SP84_ISO_build_log#2]
Hi, odd request but could you include your Bootmapper .hex file?

**Comment by peverett** [comment]
Argh! The keyboard is now at my office and I am WFH (again for the foreseeable). Sorry, it may be a while before I can do that.

**Comment by Gareth-Rouse** [comment]
No worry's ... have the same keyboard and manged to just wipe my hex file without a backup ... was hopping to avoid painstakingly adding each key.

**Comment by peverett** [comment]
Ouch!
Post to www.reddit.com/r/mechanicalkeyboards. Someone will help you, I am sure.
