### ISSUE TITLE
Provide CAD files

### ISSUE THREAD

**Issue by woelper** [peverett/YMDK75_SP84_ISO_build_log#3]
Hello and many thanks for the super helpful build log. It inspired me to print my own plates (or possibly have them cut from carbon). However, I plan on doing individual layers still and would be super happy if you could provide/export the CAD files used to make the STLs so I can create a template for a layer from them. Would this be possible?

Thanks in advance!

**Comment by peverett** [comment]
Hi, I used Tinkercad (an on-line 3D CAD tool - Basic but versatile) - As well as the STL files I put in the report, I can export the models as:

- OBJ
- GLTF
- SVG - for Laser cutting.

Maybe the last format is the most useful for you, please let me know I and I will add those files to the repo.

**Comment by woelper** [comment]
SVG would be brilliant! Thanks for looking into this!

**Comment by peverett** [comment]
I've added the SVG files to https://github.com/peverett/YMDK75_SP84_ISO_build_log/tree/master/case_models

Hope they work for you!

**Comment by woelper** [comment]
Thank you so much! 
Both bottom halves work, but unfortunately, the top SVGs are empty (you can tell by looking at the source). Would those be possible to export? Otherwise I'll try reverse engineering something with the bottom layouts.

Thanks!

**Comment by peverett** [comment]
It might be because, to get a better screen shot, the top part of the case is 'floating' above the work space Z plan. When I export other formats, that doesn't seem to be a problem. This evening, when I have time, I will go into Tinkercad, move them to the workplane (0 Z axis) and export again, and this time, I'll check the file size.

**Comment by peverett** [comment]
I have put the top case models on the Z plane (flat side down) and re-exported them. Please try and see if the updated SVG files work better for you...
- YMDK-SP84-left-top.svg
- YMDK-SP84-right-top.svg

**Comment by woelper** [comment]
Looks perfect, you are the best!

**Comment by peverett** [comment]
If you have time, please let me know how your project turns out (or post to r/mechanicalkeyboards on reddit :)
