### ISSUE TITLE
bootmapper update problem

### ISSUE THREAD

**Issue by jun0-ds** [peverett/YMDK75_SP84_ISO_build_log#5]
Hi, thanks for your content

My insert key works as a home key, so i tried to update the firmware with ps2avrGB_firmware_V1.5.0_190822.

But it crushed. I'm finding a way to reset the pcb plate.

Do you how to reset the pcb plate?

**Comment by peverett** [comment]
Hi, there is no reset button on the PCB. You can only power-cycle the board. If the flash is corrupted, I am not sure how you could reflash a default image.

**Comment by jun0-ds** [comment]
Thanks for answering.
